services:
  # n8n web service configuration
  - type: web
    name: n8n-instance
    env: docker
    docker:
      image: 'docker.n8n.io/n8nio/n8n:latest'
    envVars:
      - key: N8N_EDITOR_BASE_URL
        value: 'https://${{ services.n8n-instance.url }}'
      - key: WEBHOOK_URL
        value: 'https://${{ services.n8n-instance.url }}/webhook'
      - key: N8N_HOST
        value: '${{ services.n8n-instance.host }}'
      - key: GENERIC_TIMEZONE
        value: 'UTC' # Change to your timezone
      - key: NODE_ENV
        value: 'production'
      - key: N8N_ENCRYPTION_KEY
        value: '${{ secrets.N8N_ENCRYPTION_KEY }}'
      - key: NODE_OPTIONS
        value: '--max-old-space-size=2048'
      - key: EXECUTIONS_MODE
        value: 'queue'
      - key: NODE_FUNCTION_ALLOW_EXTERNAL
        value: '*'
      - key: EXECUTIONS_QUEUE
        value: 'redis'
      - key: QUEUE_HEALTH_CHECK_ACTIVE
        value: 'true'
      - key: QUEUE_BULL_REDIS_HOST
        value: '${{ services.redis.internalAddress }}'
      - key: QUEUE_BULL_REDIS_PORT
        value: '6379'
      - key: QUEUE_BULL_REDIS_PASSWORD
        value: '${{ secrets.REDIS_PASSWORD }}'
      - key: DB_TYPE
        value: 'postgresdb'
      - key: DB_POSTGRESDB_HOST
        value: '${{ services.postgres.internalAddress }}'
      - key: DB_POSTGRESDB_DATABASE
        value: 'n8n_db'
      - key: DB_POSTGRESDB_USER
        value: 'n8n_user'
      - key: DB_POSTGRESDB_PASSWORD
        value: '${{ secrets.DB_POSTGRESDB_PASSWORD }}'
    volumes:
      - name: n8n-data
        mountPath: /home/node/.n8n
        sizeGB: 2

  # PostgreSQL private service configuration
  - type: private-service
    name: postgres
    env: postgres-14 # Use the latest stable version supported by Render
    envVars:
      - key: POSTGRES_DB
        value: 'n8n_db'
      - key: POSTGRES_USER
        value: 'n8n_user'
      - key: POSTGRES_PASSWORD
        value: '${{ secrets.DB_POSTGRESDB_PASSWORD }}'

  # Redis private service configuration
  - type: private-service
    name: redis
    env: redis-6 # Use the latest stable version supported by Render
    envVars:
      - key: REDIS_PASSWORD
        value: '${{ secrets.REDIS_PASSWORD }}'
