services:
  - type: web
    name: n8n
    env: docker
    plan: standard
    region: oregon
    envVars:
      - key: EXECUTIONS_DATA_SAVE_MANUAL_EXECUTIONS
        value: "true"
      - key: EXECUTIONS_DATA_SAVE_ON_ERROR
        value: "all"
      - key: EXECUTIONS_DATA_SAVE_ON_SUCCESS
        value: "all"
      - key: N8N_LOG_LEVEL
        value: "info"
      - key: EXECUTIONS_DATA_PRUNE
        value: "true"
      - key: EXECUTIONS_DATA_MAX_AGE
        value: "672"
      - key: NODE_TLS_REJECT_UNAUTHORIZED
        value: "1"
      - key: N8N_METRICS
        value: "true"
      - key: QUEUE_HEALTH_CHECK_ACTIVE
        value: "true"
    healthCheckPath: "/"
    disk:
      name: n8nDisk
      mountPath: "/home/node/.n8n"
      sizeGB: 10
  - type: redis
    name: n8n-redis
    plan: starter
    env: docker

databases:
  - name: n8nDB
    plan: starter
