services:
  - type: web
    name: n8n-app
    env: docker
    dockerfilePath: Dockerfile # Ensure this Dockerfile uses the n8n-puppeteer image and configures it according to your needs.
    envVars:
      - key: WEBHOOK_URL
        value: "${N8N_WEBHOOK_URL}" # Specify your actual webhook URL
      - key: GENERIC_TIMEZONE
        value: "Europe/Bucharest"
      - key: NODE_ENV
        value: "production"
      - key: N8N_ENCRYPTION_KEY
        value: "LnGMcaSProKXSD443aI5PzXA0N8sLxJ3P2X17"
      - key: NODE_OPTIONS
        value: "--max-old-space-size=2048"
      - key: EXECUTIONS_MODE
        value: "queue"
      - key: NODE_FUNCTION_ALLOW_EXTERNAL
        value: "*"
      - key: EXECUTIONS_QUEUE
        value: "redis"
      - key: QUEUE_HEALTH_CHECK_ACTIVE
        value: "true"
    buildCommand: "" # If additional build steps are needed, specify them here.
    numInstances: 1 # Adjust based on your requirement
    plan: starter # Adjust the plan as needed.
    port: 5678
    healthCheckPath: "/" # Adjust if there's a specific health check endpoint.
    disk:
      name: n8n-disk
      mountPath: /home/node/.n8n
      sizeGB: 2 # Adjust according to your needs.

  - type: pserv # Background service for worker
    name: n8n-worker
    env: docker
    dockerfilePath: Dockerfile # This Dockerfile should configure the worker command.
    envVars: # Repeat the envVars from the n8n-app service or any worker-specific variables.
      - key: COMMAND
        value: "worker --concurrency=10"
    numInstances: 8 # Number of worker instances
    plan: starter # Adjust the plan as needed.

  # Assuming Redis is managed similarly to how services are defined
  - type: web # Render doesn't have a direct Redis service type, so you would typically use a web or background worker type, depending on your setup.
    name: n8n-redis
    env: docker
    dockerImage: redis:6-alpine
    plan: starter
    healthCheckPath: "/"

databases:
  - name: n8n-pgdb
    plan: starter # Choose the appropriate plan for your PostgreSQL database.
    envVars:
      - key: DB_TYPE
        value: "postgresdb"
      - key: DB_POSTGRESDB_DATABASE
        value: "n8n_db"
      - key: DB_POSTGRESDB_USER
        value: "n8n_db"
      - key: DB_POSTGRESDB_PASSWORD
        value: "n8n_pwd"
